### ISSUE TITLE
Example file double equals

### ISSUE THREAD

**Issue by HansHauge** [abdhass/telegram-channel-scraper#5]
In the [example file](https://github.com/abdhass/telegram-channel-scraper/blob/master/.env.example#L5) we specify file locations with a double equals `==` instead of a single equals `=`. This causes the program to look for a directory that starts with an equals sign.

eg. `=storage/telegram.json` instead of `storage/telegram.json`.

Current:

```
...
TELEGRAM_FILE==storage/telegram.json
DB_FILE==storage/db.json
CHAR_FILE==storage/chat.json
```

Suggested:

```
...
TELEGRAM_FILE=storage/telegram.json
DB_FILE=storage/db.json
CHAR_FILE=storage/chat.json
```

**Comment by abdhass** [comment]
Thanks for the suggestion. I don't know how that slipt through!
