### ISSUE TITLE
Phone number banned

### ISSUE THREAD

**Issue by GuysmoB** [abdhass/telegram-channel-scraper#8]
Hi,

I successfully run the program.
I saw all my channels but I didn't get time to chosse then my phone number was banned in few seconds.

Why ?

Thanks

**Comment by sosoced** [comment]
Hello, I have exactly the same problem

**Comment by abdhass** [comment]
Hi sorry for late reply. do you still face this problem?

**Comment by GuysmoB** [comment]
Hi,I’m not working on this project anymore.Thanks anyway Provenance : Courrier pour Windows 10 De : Abdul HassanEnvoyé le :mercredi 29 juillet 2020 18:54À : abdhass/telegram-channel-scraperCc : Remi; AuthorObjet :Re: [abdhass/telegram-channel-scraper] Phone number banned (#8) Hi sorry for late reply. do you still face this problem?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
